### ISSUE TITLE
Hide Page Filter Only Works on Daily Note Page

### ISSUE THREAD

**Issue by rcavin** [mlava/hide-topbar-buttons#1]
Hi Mark, really liking the Hide Topbar Buttons Roam Extension. Maybe it's by design, but the Hide Page Filter option only works for me on the current Daily Notes Page. I tried Hide on Mobile and Hide on All Platforms. If I go to yesterday or tomorrow using the Yesterday & Tomorrow extension or go to any standard page, the Page Filter reappears. I tried hiding the Page Filter using CSS, but couldn't differentiate it from the Linked References Filter, so this extension was a welcome find. Thanks, Bob

**Comment by mlava** [comment]
Hi @rcavin thanks for bringing this to my attention.
I've created a fix and it's pending approval in Roam Depot github: https://github.com/Roam-Research/roam-depot/pull/757
Cheers!

**Comment by mlava** [comment]
Closing as completed

**Comment by rcavin** [comment]
Hi Mark, saw this Hide Topbar Buttons update got accepted by Roam and can
report that page filter icon no longer appears for me on mobile and web
after I switch away from the Daily Note Page. Thanks, Bob

**Comment by mlava** [comment]
Hi @rcavin 
Thanks, I was going to let you know, but glad it's working!
Thanks for letting me know the issue.
Cheers!
